'use strict';
const studentId=new URLSearchParams(location.search).get('id'),backLink=document.querySelector('#backToHomework'),room=document.querySelector('#petRoom'),shop=document.querySelector('#petShop'),message=document.querySelector('#petMessage');let buying=false;
const items=[
{id:'bowlWater',name:'Миска с водой',price:1,image:'bowl-water.png',roomClass:'pet-water'},
{id:'bowlFood',name:'Миска с кормом',price:2,image:'bowl-food.png',roomClass:'pet-food'},
{id:'bowlMilk',name:'Миска с молоком',price:2,image:'bowl-milk.png',roomClass:'pet-milk'},
{id:'mouse',name:'Игрушечная мышка',price:3,image:'toy-mouse.png',roomClass:'pet-mouse'},
{id:'yarn',name:'Клубок',price:3,image:'yarn.png',roomClass:'pet-yarn'},
{id:'scratcher',name:'Когтеточка',price:6,image:'scratcher.png',roomClass:'pet-scratcher'},
{id:'armchair',name:'Кресло',price:8,image:'armchair.png',roomClass:'pet-armchair'},
{id:'sofa',name:'Диванчик',price:10,image:'sofa.png',roomClass:'pet-sofa'}];
if(studentId)backLink.href=`student.html?id=${encodeURIComponent(studentId)}`;
function render(pet={}){const balance=Number(pet.coinsBalance)||0,owned=pet.ownedItems||{},count=items.filter(i=>owned[i.id]===true).length;document.querySelector('#coinsBalance').textContent=balance;document.querySelector('#roomProgress').textContent=`Комната: ${count} из ${items.length} предметов`;document.querySelector('#petComplete').hidden=count!==items.length;room.querySelectorAll('[data-pet-item]').forEach(e=>e.remove());items.filter(i=>owned[i.id]===true).forEach(i=>{const image=document.createElement('img');image.className=`pet-item ${i.roomClass}`;image.dataset.petItem=i.id;image.src=`assets/pet/${i.image}`;image.alt=i.name;room.append(image)});shop.innerHTML=items.map(i=>{const ownedItem=owned[i.id]===true,canBuy=balance>=i.price;return`<article class="pet-product ${ownedItem?'is-owned':''}"><div class="pet-product-image"><img src="assets/pet/${i.image}" alt="${i.name}"></div><h3>${i.name}</h3><div class="pet-product-footer"><span class="pet-price"><img src="assets/pet/domocoin.png" alt="DomoCoin">${i.price}</span><button type="button" data-buy="${i.id}" ${ownedItem||!canBuy||buying?'disabled':''}>${ownedItem?'Куплено ✓':'Купить'}</button></div></article>`}).join('')}
shop.addEventListener('click',async e=>{const button=e.target.closest('[data-buy]');if(!button||buying||!studentId)return;const item=items.find(i=>i.id===button.dataset.buy);if(!item)return;buying=true;message.textContent='';try{const result=await FirebaseStore.database.ref(`students/${studentId}/pet`).transaction(pet=>{pet=pet||{};pet.ownedItems=pet.ownedItems||{};const balance=Number(pet.coinsBalance)||0;if(pet.ownedItems[item.id]===true||balance<item.price)return;pet.coinsBalance=balance-item.price;pet.ownedItems[item.id]=true;return pet});message.textContent=result.committed?`${item.name} теперь в комнате!`:'Не хватает монет'}catch(error){console.error(error);message.textContent='Не удалось выполнить покупку. Проверьте интернет.'}finally{buying=false}});
async function start(){if(!studentId){message.textContent='В адресе не указан ID ученика.';render();return}try{await FirebaseStore.migrateLocalDataOnce();await FirebaseStore.migrateHomeworkStructureOnce();await FirebaseStore.grantCompletedHomeworkCoins(studentId);FirebaseStore.database.ref(`students/${studentId}/pet`).on('value',s=>render(s.val()||{}),error=>{console.error(error);message.textContent='Firebase временно недоступна.';render()})}catch(error){console.error(error);message.textContent='Не удалось загрузить комнату. Проверьте интернет.';render()}}start();
